import React, { useState } from 'react';
import {
  X,
  Download,
  FileCode,
  FileText,
  Clipboard,
  Check,
  ShieldAlert
} from 'lucide-react';
import { StaticAnalysisResult } from '../types';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  outputCode: string;
  confidence: number;
  explanation?: string;
  staticAnalysis: StaticAnalysisResult | null;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  outputCode,
  confidence,
  explanation,
  staticAnalysis
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const headerNotice = `-- Generated by AI Lua/Luau Deobfuscator
-- Analysis confidence: ${confidence}%
-- Notice: This output is produced via static reverse engineering and AI semantic reconstruction.
-- Behavioral equivalence cannot be guaranteed 100% under all edge cases.

`;

  const finalSourceCode = headerNotice + outputCode;

  const downloadFile = (content: string, filename: string, mime: string) => {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleExportLua = () => {
    downloadFile(finalSourceCode, 'deobfuscated_script.lua', 'text/plain;charset=utf-8');
  };

  const handleExportLuau = () => {
    downloadFile(finalSourceCode, 'deobfuscated_script.luau', 'text/plain;charset=utf-8');
  };

  const handleExportTxt = () => {
    downloadFile(finalSourceCode, 'deobfuscated_script.txt', 'text/plain;charset=utf-8');
  };

  const handleExportReport = () => {
    const report = `# AI Lua/Luau Deobfuscator Analysis Report

- **Date:** ${new Date().toUTCString()}
- **Language:** ${staticAnalysis?.language || 'Lua/Luau'}
- **Lines of Code:** ${outputCode.split('\n').length}
- **Estimated Confidence:** ${confidence}%
- **Decoded Strings:** ${staticAnalysis?.decodedStrings.length || 0}
- **Inferred Identifiers:** ${staticAnalysis?.inferredIdentifiers.length || 0}
- **Detected Functions:** ${staticAnalysis?.functions.length || 0}

---

## Executive Summary
${explanation || 'Full semantic analysis completed.'}

---

## Security Audit Warnings
${
  staticAnalysis?.securityWarnings && staticAnalysis.securityWarnings.length > 0
    ? staticAnalysis.securityWarnings
        .map(w => `- **[${w.severity.toUpperCase()}] ${w.title}:** ${w.description}`)
        .join('\n')
    : 'No critical security violations detected.'
}

---

## Decoded String Mappings
${
  staticAnalysis?.decodedStrings && staticAnalysis.decodedStrings.length > 0
    ? staticAnalysis.decodedStrings
        .slice(0, 50)
        .map(s => `- \`${s.original}\` → \`${s.decoded}\` (${s.type})`)
        .join('\n')
    : 'None'
}

---

## Reconstructed Source Code
\`\`\`lua
${finalSourceCode}
\`\`\`
`;
    downloadFile(report, 'deobfuscator_report.md', 'text/markdown;charset=utf-8');
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(finalSourceCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div
      id="export-modal"
      className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4 text-neutral-100"
    >
      <div className="bg-neutral-900 border border-neutral-800 rounded-2xl w-full max-w-md shadow-2xl overflow-hidden flex flex-col">
        {/* Header */}
        <div className="bg-neutral-950 px-4 py-3.5 border-b border-neutral-800 flex items-center justify-between">
          <div className="flex items-center space-x-2.5">
            <div className="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
              <Download className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-semibold">Export Reconstructed Source</h3>
              <p className="text-[11px] text-neutral-400">
                Confidence stamped: {confidence}%
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg bg-neutral-800 hover:bg-neutral-750 text-neutral-400 hover:text-neutral-200 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Options */}
        <div className="p-4 sm:p-5 space-y-2.5">
          <button
            onClick={handleExportLua}
            className="w-full p-3 rounded-xl bg-neutral-950/80 hover:bg-neutral-800/80 border border-neutral-800 flex items-center justify-between text-left transition cursor-pointer"
          >
            <div className="flex items-center space-x-3">
              <FileCode className="w-5 h-5 text-emerald-400" />
              <div>
                <span className="font-semibold text-xs text-neutral-200 block">
                  Export as Lua (.lua)
                </span>
                <span className="text-[11px] text-neutral-400">
                  Standard Lua 5.1 compatible script
                </span>
              </div>
            </div>
            <Download className="w-4 h-4 text-neutral-500" />
          </button>

          <button
            onClick={handleExportLuau}
            className="w-full p-3 rounded-xl bg-neutral-950/80 hover:bg-neutral-800/80 border border-neutral-800 flex items-center justify-between text-left transition cursor-pointer"
          >
            <div className="flex items-center space-x-3">
              <FileCode className="w-5 h-5 text-blue-400" />
              <div>
                <span className="font-semibold text-xs text-neutral-200 block">
                  Export as Luau (.luau)
                </span>
                <span className="text-[11px] text-neutral-400">
                  Roblox engine and typed Luau syntax
                </span>
              </div>
            </div>
            <Download className="w-4 h-4 text-neutral-500" />
          </button>

          <button
            onClick={handleExportTxt}
            className="w-full p-3 rounded-xl bg-neutral-950/80 hover:bg-neutral-800/80 border border-neutral-800 flex items-center justify-between text-left transition cursor-pointer"
          >
            <div className="flex items-center space-x-3">
              <FileText className="w-5 h-5 text-neutral-400" />
              <div>
                <span className="font-semibold text-xs text-neutral-200 block">
                  Export as Plain Text (.txt)
                </span>
                <span className="text-[11px] text-neutral-400">
                  Universal text document with confidence stamp
                </span>
              </div>
            </div>
            <Download className="w-4 h-4 text-neutral-500" />
          </button>

          <button
            onClick={handleExportReport}
            className="w-full p-3 rounded-xl bg-neutral-950/80 hover:bg-neutral-800/80 border border-neutral-800 flex items-center justify-between text-left transition cursor-pointer"
          >
            <div className="flex items-center space-x-3">
              <FileText className="w-5 h-5 text-purple-400" />
              <div>
                <span className="font-semibold text-xs text-neutral-200 block">
                  Export Full Markdown Analysis Report (.md)
                </span>
                <span className="text-[11px] text-neutral-400">
                  Includes metrics, decoded strings, warnings, and code
                </span>
              </div>
            </div>
            <Download className="w-4 h-4 text-neutral-500" />
          </button>

          <button
            onClick={handleCopy}
            className="w-full p-3 rounded-xl bg-neutral-950/80 hover:bg-neutral-800/80 border border-neutral-800 flex items-center justify-between text-left transition cursor-pointer"
          >
            <div className="flex items-center space-x-3">
              <Clipboard className="w-5 h-5 text-amber-400" />
              <div>
                <span className="font-semibold text-xs text-neutral-200 block">
                  {copied ? 'Copied to Clipboard!' : 'Copy with Header Stamp'}
                </span>
                <span className="text-[11px] text-neutral-400">
                  Copies stamped code directly
                </span>
              </div>
            </div>
            {copied ? (
              <Check className="w-4 h-4 text-emerald-400" />
            ) : (
              <Clipboard className="w-4 h-4 text-neutral-500" />
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
